"use client";

import { useEffect, useState } from "react";

interface SiteData {
  business: {
    displayName: { text: string };
    formattedAddress: string;
    nationalPhoneNumber?: string;
    websiteUri?: string;
    rating?: number;
    userRatingCount?: number;
  };
  content: {
    headline: string;
    subheadline: string;
    about: string;
    services: string[];
    cta: string;
    tagline: string;
  };
}

export default function SitePreview() {
  const [siteData, setSiteData] = useState<SiteData | null>(null);

  useEffect(() => {
    const stored = localStorage.getItem("siteData");
    if (stored) setSiteData(JSON.parse(stored));
  }, []);

  if (!siteData) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-500">Loading...</p>
      </div>
    );
  }

  const { business, content } = siteData;

  return (
    <div className="min-h-screen bg-white">
      <section className="bg-gradient-to-br from-indigo-600 to-blue-700 text-white py-24 px-6 text-center">
        <p className="text-indigo-200 text-sm uppercase tracking-widest mb-4">{content.tagline}</p>
        <h1 className="text-5xl font-bold mb-4">{content.headline}</h1>
        <p className="text-xl text-indigo-100 mb-8 max-w-2xl mx-auto">{content.subheadline}</p>
        <button className="bg-white text-indigo-600 px-8 py-3 rounded-full font-semibold hover:bg-indigo-50 transition">{content.cta}</button>
      </section>

      <section className="py-20 px-6 max-w-3xl mx-auto text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-6">About {business.displayName?.text}</h2>
        <p className="text-gray-600 text-lg leading-relaxed">{content.about}</p>
        {business.rating && (
          <div className="mt-6 inline-flex items-center gap-2 bg-yellow-50 px-4 py-2 rounded-full">
            <span className="text-yellow-500 font-bold">{business.rating} &#9733;</span>
            <span className="text-gray-500 text-sm">{business.userRatingCount} reviews</span>
          </div>
        )}
      </section>

      <section className="bg-gray-50 py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 text-center mb-12">What We Offer</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {content.services.map((service, i) => (
              <div key={i} className="bg-white rounded-xl p-6 text-center shadow-sm">
                <p className="font-semibold text-gray-800">{service}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-6 max-w-3xl mx-auto text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-8">Get In Touch</h2>
        <div className="space-y-3 text-gray-600">
          <p>{business.formattedAddress}</p>
          {business.nationalPhoneNumber && (
            <p><a href={"tel:" + business.nationalPhoneNumber} className="text-indigo-600 hover:underline">{business.nationalPhoneNumber}</a></p>
          )}
          {business.websiteUri && (
            <p><a href={business.websiteUri} className="text-indigo-600 hover:underline" target="_blank" rel="noopener noreferrer">{business.websiteUri}</a></p>
          )}
        </div>
      </section>

      <footer className="bg-gray-900 text-gray-400 py-8 text-center text-sm">
        <p>{business.displayName?.text} · {business.formattedAddress}</p>
        <p className="mt-2 text-gray-600">Generated by GMB to Website</p>
      </footer>
    </div>
  );
}
