import { Resend } from "resend";
import { NextResponse } from "next/server";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  const { email, businessName, siteUrl } = await request.json();

  if (!email || !siteUrl) {
    return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
  }

  try {
    await resend.emails.send({
      from: "GMB to Website <onboarding@resend.dev>",
      to: email,
      subject: `Your website for ${businessName} is ready`,
      html: `
        <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto; padding: 32px 24px;">
          <h1 style="font-size: 24px; font-weight: bold; color: #111; margin-bottom: 8px;">Your site is live 🎉</h1>
          <p style="color: #555; margin-bottom: 24px;">We generated a free website for <strong>${businessName}</strong>. Bookmark the link below so you can find it again.</p>
          <a href="${siteUrl}" style="display: inline-block; background: #4f46e5; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-bottom: 24px;">View Your Website →</a>
          <p style="color: #999; font-size: 13px;">Or copy this URL: ${siteUrl}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
          <p style="color: #bbb; font-size: 12px;">Generated by GMB to Website. Want to claim this site and add a custom domain? Reply to this email.</p>
        </div>
      `,
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Resend error:", err);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}
